# Generated by Django 3.2.16 on 2023-01-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlbumLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_id", models.IntegerField(unique=True)),
                ("new_uid", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="BookLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_id", models.IntegerField(unique=True)),
                ("new_uid", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="CollectionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_id", models.IntegerField(unique=True)),
                ("new_uid", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="GameLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_id", models.IntegerField(unique=True)),
                ("new_uid", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="MovieLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_id", models.IntegerField(unique=True)),
                ("new_uid", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="SongLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_id", models.IntegerField(unique=True)),
                ("new_uid", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="ReviewLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=20)),
                ("old_id", models.IntegerField()),
                ("new_uid", models.UUIDField()),
            ],
            options={
                "unique_together": {("module", "old_id")},
            },
        ),
    ]
