# Generated by Django 3.2.16 on 2023-01-12 01:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import journal.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.PositiveSmallIntegerField(default=0)),
                ('template', models.CharField(choices=[('mark_item', 'Markitem'), ('review_item', 'Reviewitem'), ('create_collection', 'Createcollection'), ('like_collection', 'Likecollection')], max_length=50)),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.piece')),
            ],
            bases=(models.Model, journal.mixins.UserOwnedObjectMixin),
        ),
    ]
