from ..common.sites import SiteManager
from .apple_podcast import ApplePodcast
from .douban_book import DoubanBook
from .douban_movie import DoubanMovie
from .douban_music import DoubanMusic
from .douban_game import DoubanGame
from .douban_drama import DoubanDrama
from .goodreads import Goodreads
from .google_books import GoogleBooks
from .tmdb import TMDB_Movie
from .imdb import IMDB
from .spotify import Spotify
from .igdb import IGDB
from .steam import Steam
from .bangumi import Bangumi
