name: Mirror to Codeberg

on: [push, delete]

permissions:
  contents: read

jobs:
  to_codeberg:
    if: github.repository == 'neodb-social/neodb'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@codeberg.org:NeoDB/neodb.git
          ssh_private_key:
            ${{ secrets.CODEBERG_SSH_PRIVATEKEY }}
